"""
usage: ttapiutils autoimport [options] <data-source> <domain> <path>...
       ttapiutils autoimport --complete-dry-run=<audit-dir>

In the first form, <data-source> provides new timetable XML data
to be imported into <path>s on <domain>, replacing existing data.

Data produced by <data-source> is taken to be the desired state
of <path>s on <domain> after the import, so details such as
using ttapiutils deletegen to calculate deletes needed to achieve
the new state are taken care of automatically.

In the second form, the yet-unimported data from a dir created
by --audit-trail with --dry-run can be imported. This is useful
for completing an import after manually verifying behaviour.

options:
    <data-source>
        The name of the data source to use to generate the import data,
        or "-" to read Timetable XML data on stdin.

    <domain>
        The domain name of the Timetable site to perform the XML import
        on.

    <path>...
        List of timetable paths to be targeted by the import. The data
        source MUST produce data for every path listed. Pre-existing
        event data in Timetable at <domain> will be replaced by the
        data generated by the <data-source>.

    --audit-trail=<base-dir>
        Create a timestamped subdirectory of <dir> containing a record
        of the data received, generated and sent by an invocation of
        this program.

    --dry-run
        Generate all data, but don't actually perform the final
        xmlimport on the timetable site.

    -X=<param>=<value>...
        Extension parameters to send to the data source.

"""

# Data source: - for stdin, or name of generator, e.g. engineering
    - ttapiutils.autoimport.generators: engineering
# domain to upload to
# list of of paths to be affected